# Generated by Django 6.0.1 on 2026-03-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_systemsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='current_job',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
