# Generated by Django 6.0.1 on 2026-04-05 18:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_fix_repayment_flat_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plain_password',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='loanconfig',
            name='interest_rate_monthly',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.004000'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='loanconfig',
            name='max_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('100000000.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='loanconfig',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('30000000.00'), max_digits=14),
        ),
    ]
